### ISSUE TITLE
Improve application-specific language-files

### ISSUE THREAD

**Issue by sebastiaanspeck** [sebastiaanspeck/sportmonks#1]
**Is your feature request related to a problem? Please describe.**
To support multiple-language, I created an English and Dutch language-file. These files can be improved and extend it with new languages.

**Describe the solution you'd like**
The language-files (called `application.php`) for English and Dutch are a good start, but I think they can be improved and will eventually improve the localisation of this application.

**Describe alternatives you've considered**
I made a start to translate all the English labels to Dutch, but I am not yet satisfied with all translations.

**Additional context**

**TODO**
- [X] English
- [ ] Dutch
- [ ] Spanish
- [x] Italian
- [ ] Indonesian
- [ ] French
- [ ] German

**Comment by sebastiaanspeck** [comment]
I added an [EXAMPLE.md](https://github.com/sebastiaanspeck/sportmonks/blob/master/resources/lang/EXAMPLE.md) for people who want to contribute to the languages

**Comment by tribakzero** [comment]
Added spanish translations.

**Comment by sebastiaanspeck** [comment]
You can add new language by running:
php artisan trans:publish [2-letter-country code] --force
