### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by sebastiaanspeck** [sebastiaanspeck/sportmonks#29]
**Describe the solution you'd like**
The German [application.php](https://github.com/sebastiaanspeck/sportmonks/blob/master/resources/lang/de/application.php) and [cup_rounds.php](https://github.com/sebastiaanspeck/sportmonks/blob/master/resources/lang/de/cup_rounds.php) is still using the English translations. Translate it to German.

**Additional context**
#1

**Comment by saiij** [comment]
I'm on it!

**Comment by sebastiaanspeck** [comment]
Closed with #31
