### ISSUE TITLE
Translate to Italian

### ISSUE THREAD

**Issue by sebastiaanspeck** [sebastiaanspeck/sportmonks#30]
**Describe the solution you'd like**
The Italian [application.php](https://github.com/sebastiaanspeck/sportmonks/blob/master/resources/lang/it/application.php) and [cup_rounds.php](https://github.com/sebastiaanspeck/sportmonks/blob/master/resources/lang/it/cup_rounds.php) is still using the English translations. Translate it to Italian.

**Additional context**
#1

**Comment by FedeX15** [comment]
On it
