### ISSUE TITLE
Fix top scorers for excluded leagues

### ISSUE THREAD

**Issue by sebastiaanspeck** [sebastiaanspeck/sportmonks#36]
**Is your feature request related to a problem? Please describe.**
Right now the top scorers are not shown for World Cup. 
At this moment this is no issue for Champions League and Europa League, but this will become an issue when those tournaments reach knock-out phase

**Describe the solution you'd like**
Show the top scorers for the World Cup (not only the final but the whole tournament)

**Additional context**
I think we need to use aggregated endpoint here:
`$soccerAPI->topscorers()->setInclude($includeTopscorersAggregated)->aggregatedBySeasonId($league->current_season_id)->aggregatedGoalscorers->data;`

**Comment by Visovsiouk** [comment]
Can I tackle this issue?

**Comment by sebastiaanspeck** [comment]
Go ahead and try!

**Comment by Visovsiouk** [comment]
This cannot be tested with the basic sportsmonks API Plan

**Comment by sebastiaanspeck** [comment]
Still not what I want.. I will try to contact the API-supplier to ask if they know a solution
