### ISSUE TITLE
Translate countries

### ISSUE THREAD

**Issue by sebastiaanspeck** [sebastiaanspeck/sportmonks#5]
**Is your feature request related to a problem? Please describe.**
Right now the countries are still in English.

**Describe the solution you'd like**
A countries.php with the translations of the countries.

**TODO**
- [X] English
- [X] Dutch - @jatempa & @sebastiaanspeck 
- [X] Spanish - @jatempa
- [X] German - @sandroacoelho
- [X] Brazilian Portuguese - @guastallaigor 
- [X] French - @davidmohamedfr
- [x] Italian - @FedeX15 
- [x] Indonesian - @nipeharefa

**Comment by jatempa** [comment]
I want to work on this issue

**Comment by sebastiaanspeck** [comment]
Go ahead. Fork the repo and create a new branch. I am looking forward for your PR

**Comment by jatempa** [comment]
Please, can you provide me list with all countries?

**Comment by sebastiaanspeck** [comment]
Yes. I will upload a list will all countries in a moment. Do you know what I want?
In every lang/xx folder, I want a countries.php and then all countries translated to the language of that folder

**Comment by sebastiaanspeck** [comment]
[countries.txt](https://github.com/sebastiaanspeck/sportmonks/files/2477712/countries.txt)

Go ahead!

**Comment by jatempa** [comment]
I get it ! Thank you @sebastiaanspeck !

**Comment by sebastiaanspeck** [comment]
Take your time to translate them. Maybe I will add the German language-files today. If I will do this, I will notify you, so you can pull it.

**Comment by sebastiaanspeck** [comment]
I indeed added the German language-files, so update your branch with the master-branch

**Comment by sebastiaanspeck** [comment]
@jatempa any update?

**Comment by jatempa** [comment]
Hi @sebastiaanspeck I have created my branch for this issue https://github.com/jatempa/sportmonks/tree/ISSUE-5-Translate-Countries

**Comment by sebastiaanspeck** [comment]
Open a Pull Request so I can merge it into the master

**Comment by jatempa** [comment]
Now this is a work in progress, I hope to finish today for Spanish language

**Comment by sebastiaanspeck** [comment]
Ah I see. Because I saw the Spanish version and this was not complete yet. Thanks for the update. If you can create the countries.php for en and nl, I will do nl. Just do:
`"country" => "country",`

as initial countries.php for en and nl

**Comment by jatempa** [comment]
I get it !

**Comment by sebastiaanspeck** [comment]
@FedeX15 Could you translate the Italian countries.php?

**Comment by sebastiaanspeck** [comment]
@nipeharefa Could you translate the Indonesian countries.php?

**Comment by nipeharefa** [comment]
@sebastiaanspeck 
Of course.
